import Navbar from '@/components/Navbar';
import Head from 'next/head';
import Image from 'next/image';
import Main from '@/components/Main';
import About from '@/components/About';
import Skills from '@/components/Skills';
import Projects from '@/components/Projects';
import Contact from '@/components/Contact';


export default function Home() {
    // //  ?logica del cambio oscuro a claro 

    return (
        <div>
            <Head>
                <title>Alexis-Frond-end Developer</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            
            </Head>
            {/* <Navbar/> */}
            <Main/>
            <About/>
            <Skills/>
            <Projects/>
            <Contact/>
        </div>

    )
}
